### ISSUE TITLE
Standardize display of Locus and Gene labels

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#314] opened 2018-12-21 22:46 UTC
We refer to locus/gene interchangeably in the interface.  Some examples are shown below. Let's standardize.
@lreiser  what do you think?

![image](https://user-images.githubusercontent.com/4998871/50366507-e92a2a80-052e-11e9-988b-b83b2fe6e73f.png)
![image](https://user-images.githubusercontent.com/4998871/50366542-1b3b8c80-052f-11e9-82d7-9ce4ed823dcc.png)

**Comment by lreiser** [comment] 2019-02-13 19:30
@tberardini  agreed to standardize. It looks like evidence with is also fine. We can close this if the preferred term is gene.

**Comment by tberardini** [comment] 2019-02-14 23:23
Please fix typo in 'protein' (shows as 'protien') in the Evidence With hint before closing this issue.  Everything else looks good.

![image](https://user-images.githubusercontent.com/4998871/52824163-70e27000-306c-11e9-9f32-9322cb5086d6.png)

**Comment by lreiser** [comment] 2019-03-05 01:30
Still need to fix the Evidence With hint (change protien to protein)

To test  this create an annotation and choose METHOD=suppressor/enhancer interaction phenotypic evidence used in manual assertion
This will force display of evidence with data fields.

![screenshot_1610](https://user-images.githubusercontent.com/14040923/53774359-02424680-3ea3-11e9-9f92-7315ff1a36ad.png)

**Comment by lreiser** [comment] 2019-03-07 04:40
typo still there in the evidence with HINT field
e.g. a gene or protien >> to e.g. a gene or protein
![screenshot_1625](https://user-images.githubusercontent.com/14040923/53932756-16777680-4050-11e9-8ca5-e6880305640f.png)

**Comment by JKingSE** [comment] 2019-04-02 17:31
Using the reproduction steps from #312 to get the Evidence With field up, the "protien" typo in the hint for that field is still present

**Comment by lreiser** [comment] 2019-04-10 05:15
Confirmed the fix.

**Closed by lreiser** 2019-04-10 05:15 UTC
Labels: bug, front-end
